# Generated by Django 4.1.5 on 2023-01-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='facebook',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='authors',
            name='twitter',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
