# Generated by Django 4.1.5 on 2023-01-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_authors_facebook_authors_twitter'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='about_author',
            field=models.CharField(default=1, max_length=600),
            preserve_default=False,
        ),
    ]
