# Generated by Django 4.1.5 on 2023-02-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_authors_about_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='description',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
