# Generated by Django 4.1.5 on 2023-02-05 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0004_authors_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authors',
            name='description',
        ),
    ]
