# Generated by Django 4.1.5 on 2023-02-20 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_liked_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='liked_product',
            options={'verbose_name': 'Лайк', 'verbose_name_plural': 'Лайки'},
        ),
    ]
