# Generated by Django 4.1.5 on 2023-02-21 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_alter_books_author_book_alter_books_category'),
        ('users', '0005_alter_liked_product_product_alter_liked_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liked_product',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_product', to='books.books'),
        ),
    ]
