# Generated by Django 4.1.5 on 2023-01-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_alter_settings_options_settings_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_library', models.TextField(max_length=700)),
                ('history', models.TextField(max_length=1000)),
                ('photo_library', models.ImageField(upload_to='photo_library/')),
                ('employee_name', models.CharField(max_length=50)),
                ('employees_position', models.CharField(max_length=255)),
                ('facebook', models.URLField()),
                ('twitter', models.URLField()),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
    ]
