# Generated by Django 4.1.5 on 2023-01-29 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_aboutus'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='employees_photo',
            field=models.ImageField(default=1, upload_to='photo_employee/'),
            preserve_default=False,
        ),
    ]
