# Generated by Django 4.1.5 on 2023-02-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_aboutus_employees_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=50)),
                ('employees_position', models.CharField(max_length=255)),
                ('employees_photo', models.ImageField(upload_to='photo_employee/')),
                ('facebook', models.URLField()),
                ('twitter', models.URLField()),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Работники',
            },
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='employee_name',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='employees_photo',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='employees_position',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='twitter',
        ),
    ]
