# Generated by Django 4.1.5 on 2023-02-05 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_team_remove_aboutus_employee_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Работники', 'verbose_name_plural': 'Команда'},
        ),
    ]
