# Generated by Django 4.1.5 on 2023-02-09 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_alter_team_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='employee_name',
            new_name='worker_name',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='employees_photo',
            new_name='worker_photo',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='employees_position',
            new_name='worker_position',
        ),
    ]
