# Generated by Django 4.1.5 on 2023-01-29 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0002_authors_facebook_authors_twitter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('category', models.CharField(max_length=100)),
                ('pages', models.CharField(max_length=2000)),
                ('format', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=50)),
                ('publication_date', models.DateField()),
                ('author_book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='author_book', to='authors.authors')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
    ]
