# Generated by Django 4.1.5 on 2023-02-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_books_book_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='dimensions',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='books',
            name='publisher',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
