# Generated by Django 4.1.5 on 2023-02-09 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_books_author_description_books_author_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='author_description',
        ),
        migrations.RemoveField(
            model_name='books',
            name='author_photo',
        ),
    ]
