# Generated by Django 4.1.5 on 2023-02-10 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_remove_books_author_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_pdf',
            field=models.FileField(default=1, upload_to='books_pdf'),
            preserve_default=False,
        ),
    ]
