# Generated by Django 4.1.5 on 2023-02-11 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_alter_category_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='category_books',
        ),
    ]
