# Generated by Django 4.1.5 on 2023-02-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_rename_category_category_category_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=1, verbose_name='Человекопонятный URL'),
            preserve_default=False,
        ),
    ]
