# Generated by Django 4.1.5 on 2023-02-14 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
