# Generated by Django 4.1.5 on 2023-02-21 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0005_remove_authors_description'),
        ('books', '0015_alter_books_author_book_alter_books_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='author_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='author_book', to='authors.authors'),
        ),
        migrations.AlterField(
            model_name='books',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='category_book', to='books.category'),
        ),
    ]
